# Deployment Target
platform :ios, '8.0'

# Add pods as frameworks so we could add obj-c and swift 3.0 pods


target '${POD_NAME}_Example' do
    pod '${POD_NAME}', :path => '../'

    target '${POD_NAME}_Tests' do
        inherit! :search_paths

  ${INCLUDED_PODS}
    end
end
