# Deployment Target
platform :ios, '8.0'

# Add pods as frameworks so we could add obj-c and swift 3.0 pods
use_frameworks!

target '${POD_NAME}_Example' do
  # Development
  pod '${POD_NAME}', :path => '../'
  
  # Mine
  pod 'APExtensions', :git => 'https://github.com/APUtils/APExtensions', :branch => 'master'
end

post_install do |installer|
  # Add podInstall.command and podUpdate.command shell scripts to Pods project
  pods_project = installer.pods_project
  pods_project.new_file "../Scripts/Cocoapods/podInstall.command"
  pods_project.new_file "../Scripts/Cocoapods/podUpdate.command"
end
